parameters:
    hgabka_logger.exception_logger.class: 'Hgabka\LoggerBundle\Logger\ExceptionLogger'
    hgabka_logger.exception_notifier.class: 'Hgabka\LoggerBundle\Helper\ExceptionNotifier'

services:
    hgabka_logger.exception_logger:
        class: '%hgabka_logger.exception_logger.class%'
        arguments: ["@logger", '']

    hgabka_logger.exception_notifier:
        class: '%hgabka_logger.exception_notifier.class%'
        arguments: ["@doctrine", "@mailer", "@request_stack", "@hgabka_logger.exception_logger", "%kernel.debug%"]

    hgabka_logger.exception_listener:
        class: Hgabka\LoggerBundle\EventListener\ExceptionListener
        arguments: ["@hgabka_logger.exception_notifier"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    hgabka_logger.column_logger:
        class: Hgabka\LoggerBundle\Logger\ColumnLogger
        arguments: ["@doctrine", "@security.token_storage", '']

    hgabka_logger.action_logger:
        class: Hgabka\LoggerBundle\Logger\ActionLogger
        arguments: ["@doctrine", "@security.token_storage", "@translator", "@request_stack", "@session", '', '']

    hgabka_logger.column_log_listener:
        class: Hgabka\LoggerBundle\EventListener\ColumnLogListener
        arguments: ["@hgabka_logger.column_logger"]
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    hgabka_logger.action_log_subscriber:
        class: Hgabka\LoggerBundle\EventListener\ActionLogSubscriber
        arguments: ["@hgabka_logger.action_logger"]
        tags:
            - { name: kernel.event_subscriber }
