parameters:
    hgabka_utils.slugifier.class: 'Hgabka\UtilsBundle\Helper\Slugifier'
    hgabka_utils.shell.class: 'Hgabka\UtilsBundle\Helper\Shell\Shell'
    hgabka_utils.cipher.class: 'Hgabka\UtilsBundle\Helper\Cipher\UrlSafeCipher'
    hgabka_utils.cipher.secret: ''
    hgabka_utils.acl.helper.class: 'Hgabka\UtilsBundle\Helper\Security\Acl\AclHelper'
    hgabka_utils.acl.native.helper.class: 'Hgabka\UtilsBundle\Helper\Security\Acl\AclNativeHelper'
    hgabka_utils.security.acl.permission.map.class: 'Hgabka\UtilsBundle\Helper\Security\Acl\Permission\PermissionMap'
    hgabka_utils.clone.listener.class: 'Hgabka\UtilsBundle\EventListener\CloneListener'
    hgabka_utils.domain_configuration.class: 'Hgabka\UtilsBundle\Helper\DomainConfiguration'
    hgabka_utils.service.export.class: Hgabka\UtilsBundle\Service\ExportService
    hgabka_utils.menubuilder.class: 'Hgabka\UtilsBundle\Helper\Menu\MenuBuilder'
    hgabka_utils.admin_panel.class: 'Hgabka\UtilsBundle\Helper\AdminPanel\AdminPanel'


services:
    hgabka_utils.menu.twig.extension:
        class: Hgabka\UtilsBundle\Twig\MenuTwigExtension
        arguments: ['@hgabka_utils.menubuilder', '@hgabka_utils.admin_panel']
        tags:
        -  { name: 'twig.extension' }

    Hgabka\UtilsBundle\Helper\Menu\MenuBuilder:
        public: true
        arguments: ['@service_container']

    hgabka_utils.admin_panel:
        class: '%hgabka_utils.admin_panel.class%'

    Hgabka\UtilsBundle\AdminList\AdminListFactory:
        autowire: true
        autoconfigure: true
        public: true

    hgabka_utils.service.export:
        class:  '%hgabka_utils.service.export.class%'
        calls:
            -  [ setRenderer, [ '@templating' ] ]
            -  [ setTranslator, [ '@translator' ] ]

    hgabka_utils.adminlist_twig.extension:
        class: Hgabka\UtilsBundle\Twig\AdminListTwigExtension
        tags:
            -  { name: twig.extension }
        arguments:
            -  '@service_container'
    hgabka_utils.roman:
        class: Hgabka\UtilsBundle\Helper\Number\RomanHelper

    Hgabka\UtilsBundle\Helper\Shell\Shell:
        public: true
        autowire: true
        autoconfigure: true

    hgabka_utils.shell:
        alias: Hgabka\UtilsBundle\Helper\Shell\Shell

    hgabka_utils.cipher:
        class: '%hgabka_utils.cipher.class%'
        arguments: ['%hgabka_utils.cipher.secret%']

    hgabka_utils.slugifier:
        class: '%hgabka_utils.slugifier.class%'

    hgabka_utils.twig.extension:
        class: Hgabka\UtilsBundle\Twig\UtilitiesTwigExtension
        arguments: ['@hgabka_utils.slugifier']
        tags:
            - { name: twig.extension }

    hgabka_utils.form.type.autocomplete_entity_type:
        class: Hgabka\UtilsBundle\Form\Type\EntityAutocompleteType
        arguments:  ['@doctrine']
        tags:
            - { name: form.type }

    hgabka_utils.form.type.dynamic_collection_type:
        class: Hgabka\UtilsBundle\Form\Type\DynamicCollectionType
        arguments:  ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    hgabka_utils.form.type.dynamic_element_type:
        class: Hgabka\UtilsBundle\Form\Type\DynamicElementType
        tags:
            - { name: form.type }

    hgabka_utils.form.type.plain_widget:
        class: Hgabka\UtilsBundle\Form\Type\StaticControlType
        arguments: ['@twig']
        tags:
            - { name: form.type }

    hgabka_utils.form.type.locale_type:
        class: Hgabka\UtilsBundle\Form\Type\LocaleType
        arguments:  ['@hgabka_utils.hgabka_utils']
        tags:
            - { name: form.type }

    Hgabka\UtilsBundle\Helper\HgabkaUtils:
        arguments:  ["@service_container"]
        alias:
        public: true

    hgabka_utils.breadcrumb_manager:
        class: Hgabka\UtilsBundle\Breadcrumb\BreadcrumbManager
        arguments:  ["@security.helper", "@request_stack"]

    hgabka_utils.number_to_text:
        class: Hgabka\UtilsBundle\Helper\Number\NumberToText

    hgabka_utils.fill_filter:
        class: Hgabka\UtilsBundle\Imagine\Filter\Loader\FillFilterLoader
        tags:
            - { name: "liip_imagine.filter.loader", loader: hg_fill }

    hgabka_utils.fit_filter:
        class: Hgabka\UtilsBundle\Imagine\Filter\Loader\FitFilterLoader
        arguments: ["@liip_imagine"]
        tags:
            - { name: "liip_imagine.filter.loader", loader: hg_fit }

    hgabka_utils.paste_filter:
        class: Hgabka\UtilsBundle\Imagine\Filter\Loader\PasteFilterLoader
        arguments: ["@liip_imagine"]
        tags:
            - { name: "liip_imagine.filter.loader", loader: hg_paste }

    hgabka_utils.form.recaptcha_type:
        class: Hgabka\UtilsBundle\Form\Type\RecaptchaType
        arguments: ['']
        tags:
            - { name: form.type }

    hgabka_utils.validator.recaptcha:
        class: Hgabka\UtilsBundle\Validator\Constraints\RecaptchaValidator
        arguments: ["@request_stack", "@hgabka_utils.hgabka_utils", '']
        tags:
            - { name: validator.constraint_validator }

    hgabka_utils.breadcrumb_twig_extension:
        class: Hgabka\UtilsBundle\Twig\Extension\BreadcrumbTwigExtension
        arguments: ['@hgabka_utils.breadcrumb_manager']
        public: false
        tags:
            - { name: twig.extension }

    Hgabka\UtilsBundle\Helper\CloneHelper:
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher']

    hgabka_utils.clone.helper:
        alias: Hgabka\UtilsBundle\Helper\CloneHelper

    hgabka_utils.doctrine_mapping.listener:
        class: Hgabka\UtilsBundle\EventListener\MappingListener
        arguments: ['%hgabka_utils.backend_user_class%']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    hgabka_utils.form.helper:
        class: Hgabka\UtilsBundle\Helper\FormHelper

    hgabka_utils.formtools.twig.extension:
        class: Hgabka\UtilsBundle\Twig\FormToolsExtension
        arguments: ['@hgabka_utils.form.helper']
        tags:
            - { name: 'twig.extension' }

    hgabka_utils.sidebar.twig.extension:
        class: Hgabka\UtilsBundle\Twig\SidebarTwigExtension
        tags:
            - { name: twig.extension }

    hgabka_utils.tabs.twig.extension:
        class: Hgabka\UtilsBundle\Twig\TabsTwigExtension
        tags:
            - { name: twig.extension }

    hgabka_utils.permission_creator:
        class: Hgabka\UtilsBundle\Helper\Creators\ACLPermissionCreator
        arguments: ['@security.acl.provider', '@security.acl.object_identity_retrieval_strategy']

    hgabka_utils.cache:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%kernel.cache_dir%/hgutilscache']

    Hgabka\UtilsBundle\Helper\Security\Acl\Permission\PermissionAdmin:
        public: true
        autowire: true
        autoconfigure: true
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.acl.provider', '@security.acl.object_identity_retrieval_strategy', '@event_dispatcher', '@hgabka_utils.shell', '@kernel']

    hgabka_utils.permissionadmin:
        alias: Hgabka\UtilsBundle\Helper\Security\Acl\Permission\PermissionAdmin

    hgabka_utils.permissions.twig.extension:
        class: Hgabka\UtilsBundle\Twig\AdminPermissionsTwigExtension
        tags:
            -  { name: 'twig.extension' }

    Hgabka\UtilsBundle\Helper\Security\Acl\AclHelper:
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.role_hierarchy', '@security.acl.object_identity_retrieval_strategy','@security.acl.provider', '%hgabka_utils.public_access_role%']

    Hgabka\UtilsBundle\Helper\Security\Acl\AclNativeHelper:
        public: true
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@security.role_hierarchy', '%hgabka_utils.public_access_role%']

    Hgabka\UtilsBundle\Helper\Security\Acl\Permission\PermissionMap:
        public: true
        autowire: true
        autoconfigure: true

    hgabka_utils.security.acl.permission.map:
        alias: Hgabka\UtilsBundle\Helper\Security\Acl\Permission\PermissionMap

    hgabka_utils.security.acl.voter:
        class: Hgabka\UtilsBundle\Helper\Security\Acl\Voter\AclVoter
        arguments: ['@security.acl.provider', '@security.acl.object_identity_retrieval_strategy', '@security.acl.security_identity_retrieval_strategy', '@hgabka_utils.security.acl.permission.map']
        tags:
            - { name: security.voter, priority: 255 }
            - { name: monolog.logger, channel: security }
        # small performance boost
        public: false

    hgabka_utils.clone.listener:
        class: '%hgabka_utils.clone.listener.class%'
        tags:
            - { name: kernel.event_listener, event: hgabka_utils.onDeepCloneAndSave, method: onDeepCloneAndSave }

    hgabka.utils.array.datagrid.builder:
        class: Hgabka\UtilsBundle\Datagrid\ArrayDatagridBuilder
        arguments: ['@form.factory', '@sonata.admin.builder.filter.factory', '@sonata.admin.guesser.orm_datagrid_chain', '%form.type_extension.csrf.enabled%']
        public: true

#    hgabka_utils.logger.processor.user:
#        class: Hgabka\UtilsBundle\Helper\UserProcessor
#        arguments: [ '@service_container' ]
#        tags:
#        - { name: monolog.processor, method: processRecord }
#        - { name: hgabka_utils.logger.processor, method: processRecord }

    hgabka_utils.logger.handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments: ['%kernel.logs_dir%/hgabka_utils_%kernel.environment%.log', 10]

    hgabka_utils.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [hgabka_utils]
        calls:
        - [pushHandler, ['@hgabka_utils.logger.handler']]

    hgabka_utils.domain_configuration:
        class: '%hgabka_utils.domain_configuration.class%'
        arguments: ['@service_container']

    hgabka_utils.adminlist_factory:
        alias: Hgabka\UtilsBundle\AdminList\AdminListFactory
        
    hgabka_utils.hgabka_utils:
        alias: Hgabka\UtilsBundle\Helper\HgabkaUtils

    hgabka_utils.acl.helper:
        alias: Hgabka\UtilsBundle\Helper\Security\Acl\AclHelper
        public: true


    Hgabka\UtilsBundle\Breadcrumb\BreadcrumbManager: "@hgabka_utils.breadcrumb_manager"
    Hgabka\UtilsBundle\Helper\Slugifier: '@hgabka_utils.slugifier'
    Hgabka\UtilsBundle\Helper\Number\RomanHelper: '@hgabka_utils.roman'
    Hgabka\UtilsBundle\Datagrid\ArrayDatagridBuilder: '@hgabka.utils.array.datagrid.builder'

    hgabka_utils.menubuilder:
        alias: Hgabka\UtilsBundle\Helper\Menu\MenuBuilder

    hgabka_utils.acl.native.helper:
        alias: Hgabka\UtilsBundle\Helper\Security\Acl\AclNativeHelper

    hgabka_utils.localeswitcher.twig.extension:
        class: Hgabka\UtilsBundle\Twig\LocaleSwitcherTwigExtension
        arguments: ['@hgabka_utils.hgabka_utils']
        tags:
        -  { name: 'twig.extension' }

    Hgabka\UtilsBundle\Datagrid\CustomDatagridBuilder:
        public: true
        arguments: ['@form.factory', '@sonata.admin.builder.filter.factory', '@sonata.admin.guesser.orm_datagrid_chain', '%form.type_extension.csrf.enabled%']
        autowire: false

    hgabka_utils.asset.tag_renderer:
        class: Hgabka\UtilsBundle\Asset\TagRenderer
        arguments: ['@webpack_encore.entrypoint_lookup_collection', '@assets.packages', []]
        tags:
            - { name: kernel.reset, method: reset }

    hgabka_utils.advanced_entry_files.twig.extension:
        class: Hgabka\UtilsBundle\Twig\Extension\AdvancedEntryFilesTwigExtension
        arguments: ['@hgabka_utils.asset.tag_renderer']
        tags:
            -  { name: 'twig.extension' }

    hgabka_utils.google_drive_downloader:
        class: Hgabka\UtilsBundle\Google\DriveDownloader
        autowire: true
        arguments: ['@hgabka_utils.hgabka_utils', '', '', '']

    Hgabka\UtilsBundle\Google\DriveDownloader:
        alias: hgabka_utils.google_drive_downloader

    Hgabka\UtilsBundle\Export\ExportFieldDescriptor:
        shared: false
        autowire: true
    
    Hgabka\UtilsBundle\Validator\TaxValidator:
        public: false
        autoconfigure: true
        autowire: true

    Hgabka\UtilsBundle\Validator\Constraints\TaxIdValidator:
        public: false
        autoconfigure: true
        autowire: true

    Hgabka\UtilsBundle\Validator\Constraints\TaxNoValidator:
        public: false
        autoconfigure: true
        autowire: true
    
    Hgabka\UtilsBundle\Security\UserProvider:
        public: false
        autoconfigure: true
        autowire: true
        arguments:
            $userClass: '%hgabka_utils.backend_user_class%'
            
    Hgabka\UtilsBundle\Security\AdminLoginAuthenticator:
        public: false
        autoconfigure: true
        autowire: true
         
    Hgabka\UtilsBundle\Form\AdminLoginForm:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Model\UserManager:
        public: false
        autowire: true
        autoconfigure: true
        arguments:
            $userClass: '%hgabka_utils.backend_user_class%'

    Hgabka\UtilsBundle\Util\PasswordUpdater:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Util\UserManipulator:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Command\CreateUserCommand:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Command\UpdateAclCommand:
        public: false
        autowire: true
        autoconfigure: true
        arguments:
            $roles: '%security.role_hierarchy.roles%'
        calls:
            - [ setAclProvider, [ '@security.acl.provider' ] ]
            - [ setOiaStrategy, [ '@security.acl.object_identity_retrieval_strategy' ] ]

    Hgabka\UtilsBundle\Command\ApplyAclCommand:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Command\PromoteUserCommand:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Command\DemoteUserCommand:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Controller\SortableCRUDController:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Controller\UrlChooserCRUDController:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Controller\NestedTreeCRUDController:
        public: false
        autowire: true
        autoconfigure: true

    Hgabka\UtilsBundle\Util\TokenGenerator:
        public: false
        autowire: true
        autoconfigure: true
    
    Hgabka\UtilsBundle\Security\Md5PasswordHasher:
        public: false
        autowire: true
        autoconfigure: true
