<?php

namespace Hgabka\UtilsBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;

abstract class AbstractSortableAdmin extends AbstractAdmin
{
    protected $sortField = 'position';

    protected $datagridValues = [
        '_per_page' => \PHP_INT_MAX,
        '_sort_direction' => 'ASC',
    ];

    protected $perPageOptions = [\PHP_INT_MAX];
    protected $maxPerPage = \PHP_INT_MAX;

    public function getFilterParameters()
    {
        $parameters = parent::getFilterParameters();
        $parameters['_sort_by'] = $this->sortField;

        return $parameters;
    }

    public function getSortField(): string
    {
        return $this->sortField;
    }

    /**
     * @return AbstractSortableAdmin
     */
    public function setSortField(string $sortField): self
    {
        $this->sortField = $sortField;

        return $this;
    }

    public function getTemplate($name)
    {
        if ('list' !== $name || !empty($this->templates['list'])) {
            return parent::getTemplate($name); // TODO: Change the autogenerated stub
        }

        return '@HgabkaUtils/Admin/Sortable/base_list.html.twig';
    }

    public function setListTemplate($template)
    {
        $this->templates['list'] = $template;
    }
}
